### ISSUE TITLE
using jspm, babel, angular2, constructor parameters

### ISSUE THREAD

**Issue by areel** [shuhei/babel-plugin-angular2-annotations#3]
Hi

I am creating a workflow using jspm 0.15.7, babel 5.4.7 and angular 2 (alpha 27).
I have the class decorators being processed correctly and now I am attempting to get the constructor parameters to be parsed when using angular 2  $Inject in constructor parameter lists.

so I have installed angular2-annotations and type-assertion using 
jspm install XXXXXX -save-dev and my config.js looks like

```
System.config({
  "baseURL": "./",
  "transpiler": "babel",
  "babelOptions": {
    "optional": [
      "runtime",
      "es7.decorators"
    ],
    "plugins": [
      "angular2-annotations",
      "type-assertion"
    ]
  }, .........
```

but I am receiving the following error

```
Potentially unhandled rejection [3] ReferenceError: Error loading "sb/components/app" at http://localhost:3000/sb/components/app.js
Unknown plugin "angular2-annotations"
    at PluginManager.subnormaliseString (http://localhost:3000/jspm_packages/npm/babel-core@5.4.7/browser.js:9222:13)
    at PluginManager.add (http://localhost:3000/jspm_packages/npm/babel-core@5.4.7/browser.js:9259:27)
    at File.buildTransformers (http://localhost:3000/jspm_packages/npm/babel-core@5.4.7/browser.js:8366:21)
    at new File (http://localhost:3000/jspm_packages/npm/babel-core@5.4.7/browser.js:8233:10)
    at TransformerPipeline.transform (http://localhost:3000/jspm_packages/npm/babel-core@5.4.7/browser.js:12103:16)
    at x.e (http://localhost:3000/jspm_packages/es6-module-loader.js:7:24001)
    at http://localhost:3000/jspm_packages/es6-module-loader.js:7:24475
    at O (http://localhost:3000/jspm_packages/es6-module-loader.js:7:7439)
    at K (http://localhost:3000/jspm_packages/es6-module-loader.js:7:7071)
    at y.7.y.when (http://localhost:3000/jspm_packages/es6-module-loader.js:7:10745)
```

any advice on how to set up my workflow would be appreciated.

Aidan

**Comment by shuhei** [comment]
Hi, It seems like babel can't find plugins by package names on jspm at this
time. https://github.com/jspm/jspm-cli/issues/778

I'm not familiar with jspm but the only chance for now might be using
absolute paths instead of package names.

**Comment by areel** [comment]
yep, will raise with JSPM,
